apiVersion: v1
kind: Service
metadata:
  name: microeks
  namespace: default
  labels:
    app: microeks
spec:
  selector:
    app: microeks
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
