apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: microeks
      context: ../../microeks
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
