name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw Executable
        run: chmod +x mvnw

      # - name: Build Application and Docker Image
        # run: ./mvnw -Pprod verify jib:dockerBuild -DskipTests -Dmaven.javadoc.skip=true -DskipITs -C

      - name: Verify Dockerfile
        run: |
          if [ -f Dockerfile ]; then
            echo "Dockerfile found!"
          else
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Push Docker Image to ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: microeks
      #     IMAGE_TAG: latest
      #   run: |
      #     docker image tag microeks 637423430820.dkr.ecr.us-east-1.amazonaws.com/microeks:latest
      #     docker push 637423430820.dkr.ecr.us-east-1.amazonaws.com/microeks:latest

      - name: Set Up kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
          kubectl config use-context arn:aws:eks:us-east-1:637423430820:cluster/${{ secrets.EKS_CLUSTER_NAME }}
          kubectl config current-context

      - name: Verify Kubernetes Access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy Microservices Using JHipster Script
        run: |
          cd kubernetes
          bash kubectl-apply.sh -f

      - name: Verify Deployment
        run: |
          kubectl get svc microeks

      - name: Verify Public IP
        run: |
          echo "Waiting for Load Balancer to provision..."
          while [[ $(kubectl get svc microeks -o jsonpath='{.status.loadBalancer.ingress[0].hostname}') == "" ]]; do
            sleep 10
          done
          EXTERNAL_IP=$(kubectl get svc microeks -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Application is accessible at http://${EXTERNAL_IP}"
